version: '3'
services:
  node-app:
    build: .
    ports:
      - '8090:8090'
    environment:
      - PORT=8090

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hyoryu
      - MONGO_INITDB_ROOT_PASSWORD=password
